apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::204900921054:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-bsidrsqriElv
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::204900921054:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-21T06:06:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1143"
  uid: e27705ae-1816-4d60-9411-888ff9b55421
